### ISSUE TITLE
Unknown version 1.28.0 in bioconducter

### ISSUE THREAD

**Issue by visze** [hansenlab/mpra#11]
Hi,

The latest bioconducter contains an mpr aversion of 1.28.0. I could not find this in the repository. The latest here is 1.27.3

Have a look here: https://bioconductor.org/packages/3.20/bioc/html/mpra.html

and here:

 https://github.com/hansenlab/mpra/blob/devel/DESCRIPTION

Cheers

**Comment by lmyint** [comment]
Hi Max,
Bioconductor releases a new version every 6 months (https://contributions.bioconductor.org/use-devel.html) and bumps version numbers automatically with these new versions. This is why 1.27.3 got bumped to 1.28.0. These package versions are the same.

Best,
Leslie
