### ISSUE TITLE
Taking strand information into account

### ISSUE THREAD

**Issue by pjlaw** [hansenlab/mpra#5]
Apologies if this is an obvious question, but how would you include strand information into the model when comparing alleles?

I have the DNA matrix as
```> head(dna_mat)
               ALT.1 REF.1 ALT.2 REF.2   ALT.3   REF.3
SNP1_fwd   4246  7552  4112  7142  2698  5100
SNP1_rev   3605  2085  3205  1926  4050  2650
```
and similar for the RNA matrix
At the moment, I have been treating them as separate (independent?) variants, and I have seen some papers where the strand information for both strands is merged together, but I don't think that either is appropriate.

I've converted the DNA and RNA matrices to be grouped by variant, e.g.
```
rsid	ALT.1_fwd	ALT.1_rev	REF.1_fwd	REF.1_rev	ALT.2_fwd	ALT.2_rev	REF.2_fwd	REF.2_rev	ALT.3_fwd	ALT.3_rev	REF.3_fwd	REF.3_rev
SNP1	4246	3605	7552	2085	4112	3205	7142	1926	2698	4050	5100	2650
```
but I'm not sure how to include the strand information into the design matrix.

Is it simply  `design <- data.frame(intcpt = 1, alleleB = grepl("ALT", colnames(mpraset)), strand = grepl("fwd", colnames(mpraset)))`
and the block would be `block <- rep(1:3, each=4)`

**Comment by lmyint** [comment]
Yes, the approach you describe at the end works to incorporate strand information and handle the correlation resulting from different alleles + strands from the same biological replicate.

**Comment by pjlaw** [comment]
Excellent. Thank you
