### ISSUE TITLE
Barcode summarization

### ISSUE THREAD

**Issue by tomoyahonda** [hansenlab/mpra#6]
Hi Leslie,

I have four replicates of MPRA experiments for both control and treated samples and I want to get a list of active promoters in treated samples. After testing  mpralm function, I got a very different result of variability versus element copy number relationship, depending on aggregate = "mean" or "sum". The "mean" (first plot) looks similar to what is published but the "sum" (second plot) shows weird plot. Do you have explanation of the difference and suggestion for how to troubleshoot the analysis?

Best,
Tomoya
![set mean](https://user-images.githubusercontent.com/34196594/206776463-e16279d7-8203-40df-a8e0-25521af24b4a.png)
![set sum](https://user-images.githubusercontent.com/34196594/206776467-1c3259c1-dc62-4c29-965e-b80bd5ab065f.png)

**Comment by lmyint** [comment]
My guess is that there is some subgroup of assayed putative regulatory elements (PREs) that has an overabundance of zeroes in the DNA or RNA counts, which might be creating the two clouds of points in the second plot. Using `aggregate = "mean"` looks like a reasonable choice for your analysis because the mean-variance relationship follows what is expected, as you noted. It is worth doing an exploratory analysis of the PREs in the two clouds to see if there are systematic differences in the counts for those two groups--my hunch is that is has something to do with the abundance of zeros--if so it's worth seeing why this happens (e.g., because of experimental design).

**Comment by tomoyahonda** [comment]
Thank you for the reply. As you pointed out, I confirmed the cloud with high SD in the 2nd plot was related to the non-zero RNA barcode counts. This should be something expected, as I deal with low input RNA samples.

I wonder if there is a way to improve the analysis. One quick thing that came to my mind is to filter out PREs with zero RNA counts before passing through mpralm. However this will reduce total PREs to be analyzed. 

The other idea is to feed more data to the mpralm analysis. I have so far used data from 2 conditions, but I have total 6 conditions (each 4 replicates). Do you think this helps the analysis? And if so, how can I create a design matrix? Currently I followed your sample: 
design <- data.frame(intcpt = 1, episomal = grepl("MT", colnames(mpraSetExample)))

Best,
Tomoya

**Comment by lmyint** [comment]
If a PRE has zero RNA or DNA counts across all barcodes and biological replicates, then it makes sense to filter out that PRE--you won't be able to learn anything meaningful about that PRE. Reducing the total # of PREs to be analyzed isn't a priori a bad thing. Hopefully the filtering doesn't remove so many that the mean-variance relationship can't be estimated.

If 6 conditions are of interest, you should analyze them all at once--you don't need to restrict yourself to just comparing 2 conditions at a time. You can create a design matrix using the `model.matrix()` function. For example, let's say your samples are ordered like this: `condition1_replicate1, condition1_replicate2, ..., condition1_replicate4, condition2_replicate1, ...`. Then you can create a design matrix as such:

```
conditions <- rep(paste0("cond", 1:6), each = 4)
design <- model.matrix(~1+conditions)
```

See Section 9.3 in the limma User's Guide (https://bioconductor.org/packages/release/bioc/vignettes/limma/inst/doc/usersguide.pdf) for details on testing and inference for different contrasts.

**Comment by tomoyahonda** [comment]
Filtering zero RNA-barcode count reduced the total PRE from 3300 to 2400 and gave the following plots. The mpralm program still worked to estimate the relationship, but the filtering made the x-axis range narrow and I don't see the tailing anymore. This is because low DNA barcode count was associated with zero RNA barcode counts (also DNA count in my dataset has small variation even before filtering). Do you see any problems on these analysis?

Best,
Tomoya

![Rplot](https://user-images.githubusercontent.com/34196594/208736879-30184fb9-0714-4b05-96b6-184f59f3ef80.png)
![Rplot01](https://user-images.githubusercontent.com/34196594/208736903-04e82589-a292-4525-9cf6-5a9db7b921e2.png)

**Comment by lmyint** [comment]
The p-value distribution looks off - it should be a mixture of a uniform distribution with a spike at low p-values but the distribution looks overly conservative. Are you using aggregate = "mean" or "sum"? And what was the exact filtering rule used? It seems like the filtering was too aggressive (removed too many PREs). Were you removing PREs with *any* zeros or with *all* zeros in DNA and/or RNA? Removing PREs with *any* zeros is too aggressive - you can still learn about regulatory activity for those PREs as long as you don't have *ALL* zeros across barcodes.

**Comment by tomoyahonda** [comment]
Here I filtered out _any zero_ in RNA and used aggregate = "sum". The histogram above is "adjusted p-value" and the histogram of "p-value" looks fine as below. I have removed PREs with any zero in RNA, otherwise I saw two clouds with high and low SD as in my first comment and the fitting of mean-variance didn't make sense.  
![Rplot](https://user-images.githubusercontent.com/34196594/209271201-208199db-d9e8-483d-b731-c730bc436684.png)

When I conducted the analysis using aggregate = "mean", the mean-variance relationship looked fine, but I got unnormal distributions in both p-value and adjusted p-value. So I was not sure. 
![Rplot01](https://user-images.githubusercontent.com/34196594/209271719-aa6442f5-8b33-464f-b995-bc5ba4c1e29b.png)
![Rplot02](https://user-images.githubusercontent.com/34196594/209271720-66b0ee0f-363d-43b8-b0be-b33aff341f34.png)

**Comment by lmyint** [comment]
Sorry I missed the fact that you plotted the adjusted p-value distribution at first. Inspecting the **raw** (unadjusted) p-value distribution is what matters--you don't need to look at the adjusted p-value distribution. The raw p-value distribution should look uniform with a spike at low p-values--which is what you have in the very first plot using "sum" aggregation and filtering out PREs with any zeros in RNA. This analysis looks sensible in terms of the mean-variance relationship you observe and the raw p-value distributions--I would recommend sticking with this analysis.

**Comment by tomoyahonda** [comment]
Thank you. I am getting the sense of my raw data and how mpralm analysis works. I close this issue.
